### ISSUE TITLE
Customer email will be used even if no customer exists

### ISSUE THREAD

**Issue by ckilb** [spryker-eco/after-pay#15]
The following line will break if there's no customer set in the OrderTransfer (guest checkout):
 
https://github.com/spryker-eco/after-pay/blob/cd9a0eccc54d6dc25a630482412544568f55e9b1/src/SprykerEco/Zed/AfterPay/Communication/Converter/OrderToCallConverter.php#L28

I guess $orderTransfer->getEmail() should be used instead.

**Comment by tvaleriy** [comment]
Hi Christian,

My name is Valerii and I'm a support engineer in Spryker.
Thank you for the report, internal ticket is created and I will notify here when it's fixed and released.

Best regards,
Valerii

**Comment by tvaleriy** [comment]
Hi Christian,

this has been fixed in https://github.com/spryker-eco/after-pay/releases/tag/1.0.2.

Best,
Spryker Support Team
