### ISSUE TITLE
Unused methods

### ISSUE THREAD

**Issue by ckilb** [spryker-eco/after-pay#16]
There are several methods in the OrderToRequestTransfer.php class that are not being used - but *should* be called in the method _buildOrderWithItemsRequestTransfer_ :

https://github.com/spryker-eco/after-pay/blob/cd9a0eccc54d6dc25a630482412544568f55e9b1/src/SprykerEco/Zed/AfterPay/Business/Payment/Mapper/OrderToRequestTransfer.php#L310

In the previous implementation of the package the method _buildOrderWithItemsRequestTransfer_  was getting a transfer object of OrderTransfer, so it was easy to pass it to the now not used methods. This has been changed to an AfterPayCallTransfer which can not be passed as the unused methods still expect an OrderTransfer.

I guess the unused methods need to be adapted, too and then be called from _buildOrderWithItemsRequestTransfer_

**Comment by tvaleriy** [comment]
Hi Christian,

My name is Valerii and I'm a support engineer in Spryker.
Thank you for the report, internal ticket is created and I will notify here when it's fixed and released.
But normally we aren't monitoring repositories for created PR's or issues. So please use http://support.spryker.com next time.
Thank you for your understanding.

Best regards,
Valerii

**Comment by alex-galych** [comment]
Hi Christian, 

thank you for the report, we have released a fix: https://github.com/spryker-eco/after-pay/releases/tag/1.0.2

Best regards,
Alex
